// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4ICjrytW0iKF6apKXzI3Ss44CCvtGKT0',
    appId: '1:742779567757:web:49c917e7893e0b9ba56cc4',
    messagingSenderId: '742779567757',
    projectId: 'milanfirebase-5a633',
    authDomain: 'milanfirebase-5a633.firebaseapp.com',
    storageBucket: 'milanfirebase-5a633.firebasestorage.app',
    measurementId: 'G-X40CTH4TJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVqiwnyjp9fYzdR5cY9B69EJY1L0fTdFI',
    appId: '1:742779567757:android:90d675ea59b394c3a56cc4',
    messagingSenderId: '742779567757',
    projectId: 'milanfirebase-5a633',
    storageBucket: 'milanfirebase-5a633.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnJHMsQiL6mbwzPlBHh25ngBGdbkTn3dg',
    appId: '1:742779567757:ios:9ffa33e859b4e834a56cc4',
    messagingSenderId: '742779567757',
    projectId: 'milanfirebase-5a633',
    storageBucket: 'milanfirebase-5a633.firebasestorage.app',
    iosBundleId: 'np.patancollege.myApp',
  );
}
